config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks 
    delete '/task_delete', to: 'tasks#destroy'
    get '/task_show', to: 'tasks#show'
  end


  root 'projects#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord

  validates :title, :description, presence: true
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :project

  validates :task_title, :task_description, :state, :deadline, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all.order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def show
    @project = set_project
  end

  def edit
    @project = set_project
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project has been created!"
    else
      flash[:notice] = "An error has occurred! Can't create the project!"
    end

  end

  def update
    @project = set_project
    if @project.update(project_params)
      redirect_to @project, notice: "Project has been updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = set_project
    @project.tasks.destroy_all
    @project.destroy
    redirect_to projects_path, notice: "Project has been deleted!"
  end


  private
  def set_project
    @project = Project.find_by(id: params[:id])
  end
  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_project, only: [:update, :show, :delete]
  def new
    #@project = set_project
    @task = Task.new
  end

  def show
    @task = set_task
  end

  def edit
    @task = set_task
  end

  def create
    #@project = set_project
    @task = Task.new(task_params)

    if @task.deadline >= Date.today
      if @task.save
        redirect_to project_tasks_path, notice: "Task has been added!"
      else
        flash[:notice] = "Something went wrong!"
      end
    else
      redirect_to project_tasks_path
      flash[:notice] = "Deadline can't be before the creation date!"
    end

  end

  def update
    @task = set_task

    if @task.update(task_params)
      redirect_to project_task_path(@task), notice: "Task has been updated!"
    else
      flash[:notice] = "Something went wrong!"
    end
  end

  def destroy
    #@task = Task.find_by(params[:id]) FOR BUTTON_TO
    @task = set_task

    if @task.destroy
      redirect_to project_path(@task.project), notice: "Task has been deleted!"
    else
      flash[:notice] = "Something went wrong!"
    end
  end

  private

  def set_task
    #@project = set_project
    @task = Task.find_by(id: params[:id])
  end

  def set_project
    @task = set_task
    @project = @task.project
  end

  def task_params
    params.require(:task).permit(:task_title, :task_description, :state, :deadline).merge(project_id: params[:project_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Project Management', root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to "New Project", new_project_path, class: "new-project-link"%>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<style>
  nav {
      box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
      backdrop-filter: blur(2.7px);
      -webkit-backdrop-filter: blur(2.7px);
      height: 4em;
      font-weight: bold;
      margin-bottom: 5em;
  }

  .navbar-brand {
      font-size: 1.5em;
  }

  .new-project-link {
      color: #EFEFEF;
      text-decoration: none;
  }
</style>

app/views/layouts/application.html.erb
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tasks Tracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

<center>
  <a style="color: green"><%= notice %></a>
  <%= render 'home/header' %>
  <%= yield %>
</center>


</body>
</html>

<style>
    body {
        background: url(<%= asset_path 'background.jpg' %>) no-repeat center center fixed;
        -webkit-background-size: cover;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(5px);
        -webkit-backdrop-filter: blur(5px);
        border: 1px solid rgba(255, 255, 255, 0.3);
        color: #E1F1FF;
    }
</style>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-container">
    <div class="field">
      <%= form.label :title , class: "form-label"%>
      <%= form.text_field :title,  class: "form-control",  placeholder: "Example : building a crypto platform"%>
    </div>

    <div class="field">
      <%= form.label :description,  class: "form-label" %>
      <%= form.text_area :description,  class: "form-control", placeholder: "Something about the project"%>
    </div>

    <div class="actions" style="margin-top: 1.5em">
      <%= form.submit class: "btn btn-primary"%>
    </div>
  </div>

<% end %>

<%= link_to "Back", projects_path %>



<style>

  .form-container {
      width: 25em;
      height: 10em;
      margin: 1em 0 1em 0;
      background: rgba(255, 255, 255, 0.06);
      border-radius: 16px;
      box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
      backdrop-filter: blur(2.7px);
      -webkit-backdrop-filter: blur(2.7px);
      border: 1px solid rgba(255, 255, 255, 0.3);
      padding: 1em;
  }


</style>

app/views/projects/edit.html.erb
<h1>Update project<h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1>
  <a class="header" href="#">Projects</a>
</h1>

<% @projects.each do |project| %>
  <div class="form-container">
    <div class="project-title-div">
      <%# project.id %><%= link_to project.title, project_path(project), class: "project-title" %>
    </div>

    <div class="project-description-div">
      <%= truncate project.description, length: 150, class: "project-description" %>
    </div>

    <div class="project-show-div">
      <%= link_to '< Show Project >', project_path(project), class: "project-show" %>
    </div>
  </div>
<% end %>

<style>

  h1 {
      margin-bottom: 3em;
  }
  .header {
      font-size: 3em;
      font-weight: bold;
      color: #EFEFEF;
      text-decoration: none;
      transition: 1s color;
  }

  .header:hover {
      color: #DF59AA;
  }

  .form-container {
      width: 25em;
      height: 15em;
      margin: 2em 0 2em 0;
      background: rgba(8, 101, 178, 0.35);
      border-radius: 16px;
      box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
      backdrop-filter: blur(5.9px);
      -webkit-backdrop-filter: blur(5.9px);
      border: 1px solid rgba(8, 101, 178, 0.2);
      padding: 2em;
      transition: 1s box-shadow, color;
  }

  .form-container:hover {
      color: #E1F1FF;
      box-shadow: 0 5px 15px #E1F1FF;
  }

  .project-title {
      font-size: 2em;
      text-decoration: none;
      font-weight: bold;
      color: #C25DB6;
  }

  .project-description {
      font-weight: normal;
      font-style: italic;
  }

  .project-show {
      font-style: inherit;
      font-weight: bold;
      text-decoration: none;
      color: #DF59AA;
  }

  .project-show-div {
      margin-top: 2em;
  }

  .project-description-div {
      margin: 0.7em 0 0.7em 0;
  }



</style>

app/views/projects/new.html.erb
<h1>New project<h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<p><%= @project.description %> </p>
<p><%= @project.id %></p>
<p><%= link_to "Edit", edit_project_path(@project) %></p>
<p><%= button_to "Destroy", @project, method: :delete %></p>

<%= link_to "Back", projects_path %>


<!-- TASKS SECTION -->

<br />
<div class="Tasks-section">
  <div class="Tasks-count"><h3><%= @project.tasks.count %> <strong> Tasks</strong></h3></div>

  <br /><hr />
  <section class="tasks-display">
    <section class="done-tasks-display">
      <h2>Done</h2>

      <%= render @project.tasks.select { |task| task.state == 'Done'} %>
    </section>

    <section class="to-do-tasks-display">
      <h2>To Do</h2>
      <%= render @project.tasks.select { |task| task.state != 'Done'} %>
    </section>
  </section>

  <section class="new-task">
    <h2>Add a new task</h2>
    <div class="form">
      <%= render partial: 'tasks/form', locals: {project: @project} %>
    </div>
  </section>
</div>

app/views/tasks/_form.html.erb
<form action="<%= project_tasks_path(project) %>" method="post">

  <input type="hidden" name="authenticity_token" value="<% form_authenticity_token %>">

  <div class="task-content">
    <input type="text" name="task[task_title]" class="title-input">
    <textarea name="task[task_description]" class="textarea-space"></textarea>
    <<!--input type="text" name="task[state]" class="state-input">-->
    <select name="task[state]" class="state-input">
      <option value="just started">Just Started</option>
      <option value="in progress">In Progress</option>
      <option value="done">Done</option>
    </select>


    <input type="date" name="task[deadline]" class="date-input">
    <button type="submit" value="Submit" class="submit-btn">Post</button>
  </div>

</form>

app/views/tasks/_task.html.erb
<p>
  <strong>Title</strong>
  <%# link_to task.task_title, project_task_path(@project, task) %>
  <%= link_to task.task_title, project_task_show_url(project_id: @project.id,id: task)%>
  <%= task.id %>
</p>

<hr />

app/views/tasks/edit.html.erb
<%= form_with(model: @task, url: [@task.project, @task]) do |form| %>
  <div class="field">
    <%= form.label :task_title %>
    <%= form.text_field :task_title %>
  </div>

  <div class="field">
    <%= form.label :task_description %>
    <%= form.text_area :task_description %>
  </div>

  <!--<div class="field">
    <%# form.label :state %>
    <%# form.text_area :state %>
  </div>-->

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, ['Just started', 'In progress', 'Done'] %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', project_task_path(@task) %>

app/views/tasks/show.html.erb
<h1><%= @task.task_title %></h1>
<p>
  <%= @task.task_description %>
</p>
<p>
  <strong>State</strong>
  <%= @task.state %>
</p>
<p>
  <Strong>Deadline</Strong>
  <%= @task.deadline %>
</p>


<%= link_to 'Edit', edit_project_task_path(@task.project, @task) %>
<%# button_to 'Delete', project_task_delete_path(@task.project, @task), method: :delete %>
<%= link_to "Destroy", [@task.project, @task], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

<%= link_to 'Back', project_path(@task.project)%>